Documentation:
- changed-files:
  - any-glob-to-any-file: docs/**

NuGet:
- changed-files:
  - any-glob-to-any-file: '**/*.nuspec'

Scripts: # Add the 'Scripts' label
- changed-files:
  - any-glob-to-any-file: '**/*.ps1' # Windows
  - any-glob-to-any-file: '**/*.sh' # Linux

regarding-events: # Add the 'Events' label
- changed-files:
  - any-glob-to-any-file: Exiled.Events/** # Any Modifications to events

regarding-api: # Add the 'API' label
- changed-files:
  - any-glob-to-any-file: Exiled.API/** # Any modifications to the API

regarding-transpiler: # Add the 'transpiler' label
- changed-files:
  - any-glob-to-any-file: Exiled.Events/Patches/**/* # Any modifications to transpiler files

CustomModules: # Add the 'CustomModules' label
- changed-files:
  - any-glob-to-any-file: Exiled.CustomModules/** # Any modifications to CustomModules

Installer: # Add the 'Installer' label
- changed-files:
  - any-glob-to-any-file: Exiled.Installer/** # Any modifications to the Installer

Localization: # Add the 'Localization' label
- changed-files:
  - any-glob-to-any-file: Localization/** # Any modifications to Localization

GitHub_Actions: # Add the 'GitHub' label
- changed-files:
  - any-glob-to-any-file: .github/** # Any modifications to github related files

